#!/bin/sh
set -e

# Only run on fresh install/upgrade and if systemd is actively running
if [ "$1" = "configure" ] && [ -d /run/systemd/system ]; then
    systemctl daemon-reload
    systemctl enable --now kerio-connect-reindex.timer || true
fi

exit 0